name: OTF Parallel Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [firefox, chrome, edge]

    name: Test on ${{ matrix.browser }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create isolated network
        run: docker network create isolated

      - name: Build AUT
        run: docker build -t my-php-site .

      - name: Run AUT
        run: docker run -d --network=isolated -p 80:80 --name docker-aut my-php-site

      - name: Start Selenium Grid
        run: |
          docker run -d --network=isolated -p 4444:4444 --name selenium-hub selenium/hub:latest

          docker run -d --network=isolated -e SE_EVENT_BUS_HOST=selenium-hub \
            -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
            -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
            selenium/node-firefox:latest

          docker run -d --network=isolated -e SE_EVENT_BUS_HOST=selenium-hub \
            -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
            -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
            selenium/node-chrome:latest

          docker run -d --network=isolated -e SE_EVENT_BUS_HOST=selenium-hub \
            -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
            -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
            selenium/node-edge:latest

      - name: Wait for Selenium
        run: sleep 15

      - name: Install Selenium client
        run: pip install -U selenium

      - name: Run test
        env:
          BROWSER: ${{ matrix.browser }}
        run: python tests/hello_aut.py http://docker-aut

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: Screenshot-${{ matrix.browser }}
          path: screenshot-${{ matrix.browser }}.png
